/********************************************************************************
** Form generated from reading UI file 'gestionlivraisons.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GESTIONLIVRAISONS_H
#define UI_GESTIONLIVRAISONS_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_GestionLivraisons
{
public:
    QTabWidget *tabWidget;
    QWidget *La_Livraison;
    QGroupBox *groupBox;
    QPushButton *pb_supprimer_liv;
    QLineEdit *le_id_supp_liv;
    QTableView *tab_Livraisons;
    QLineEdit *le_id_rech_liv1;
    QPushButton *pb_rechercher_liv;
    QPushButton *pb_pdf_liv;
    QGroupBox *groupBox_4;
    QLabel *label;
    QLineEdit *la_adresseliv;
    QLineEdit *le_id;
    QLineEdit *le_nomLiv;
    QLabel *label_2;
    QLabel *label_13;
    QLineEdit *la_Dateliv;
    QLabel *label_3;
    QPushButton *pb_Modifierliv_2;
    QPushButton *pb_Modifierliv;
    QPushButton *pb_ajouterliv;
    QLabel *label_24;
    QWidget *widget;
    QLabel *label_25;
    QWidget *widget_4;
    QPushButton *pushButton_4;
    QPushButton *pushButton_3;
    QPushButton *pb_rechercher_liv_2;
    QLineEdit *le_id_rech_liv1_2;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QWidget *La_commande;
    QGroupBox *groupBox_2;
    QPushButton *pb_ajouterCom;
    QTableView *tab_Commandes;
    QPushButton *pb_supprimer_2;
    QLineEdit *le_id_supp_co;
    QLabel *label_11;
    QPushButton *pb_trie_co;
    QPushButton *pb_date_co;
    QGroupBox *groupBox_5;
    QPushButton *pb_Modifierliv_3;
    QPushButton *pb_modifierCom;
    QLabel *label_14;
    QLineEdit *le_id_2;
    QLabel *label_6;
    QLabel *label_4;
    QLineEdit *le_Nom_Co;
    QLineEdit *le_prix_Com;
    QLabel *label_5;
    QLabel *label_15;
    QLineEdit *le_Email_CO;
    QLineEdit *le_qte_com;
    QPushButton *pb_trie_co_2;
    QPushButton *pb_date_co_2;
    QWidget *widget_2;
    QWidget *widget_3;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QLabel *label_31;
    QPushButton *pb_rechercher_liv_5;
    QLineEdit *le_id_rech_liv1_5;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QPushButton *pb_rechercher_liv_6;
    QWidget *tab;
    QGroupBox *groupBox_3;
    QPushButton *pushButton_6;
    QPushButton *pushButton_5;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QLabel *label_10;
    QLabel *label_12;
    QLabel *label_16;
    QLabel *label_17;
    QGroupBox *groupBox_6;
    QPushButton *pushButton_26;
    QPushButton *pushButton_25;
    QLabel *label_39;
    QLabel *label_40;
    QPushButton *pushButton_27;
    QLabel *label_41;
    QPushButton *pushButton_28;
    QLabel *label_42;
    QPushButton *pushButton_11;
    QPushButton *pushButton_10;
    QLabel *label_43;
    QWidget *widget_5;
    QWidget *widget_6;
    QGroupBox *groupBox_7;
    QPushButton *pushButton_29;

    void setupUi(QDialog *GestionLivraisons)
    {
        if (GestionLivraisons->objectName().isEmpty())
            GestionLivraisons->setObjectName(QStringLiteral("GestionLivraisons"));
        GestionLivraisons->resize(1114, 657);
        tabWidget = new QTabWidget(GestionLivraisons);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 1111, 671));
        tabWidget->setStyleSheet(QStringLiteral(""));
        La_Livraison = new QWidget();
        La_Livraison->setObjectName(QStringLiteral("La_Livraison"));
        groupBox = new QGroupBox(La_Livraison);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(20, 40, 1081, 581));
        groupBox->setStyleSheet(QStringLiteral(""));
        pb_supprimer_liv = new QPushButton(groupBox);
        pb_supprimer_liv->setObjectName(QStringLiteral("pb_supprimer_liv"));
        pb_supprimer_liv->setGeometry(QRect(120, 420, 93, 28));
        pb_supprimer_liv->setStyleSheet(QStringLiteral(""));
        le_id_supp_liv = new QLineEdit(groupBox);
        le_id_supp_liv->setObjectName(QStringLiteral("le_id_supp_liv"));
        le_id_supp_liv->setGeometry(QRect(40, 420, 61, 22));
        le_id_supp_liv->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        tab_Livraisons = new QTableView(groupBox);
        tab_Livraisons->setObjectName(QStringLiteral("tab_Livraisons"));
        tab_Livraisons->setGeometry(QRect(650, 70, 421, 251));
        tab_Livraisons->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        le_id_rech_liv1 = new QLineEdit(groupBox);
        le_id_rech_liv1->setObjectName(QStringLiteral("le_id_rech_liv1"));
        le_id_rech_liv1->setGeometry(QRect(780, 40, 181, 22));
        le_id_rech_liv1->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        pb_rechercher_liv = new QPushButton(groupBox);
        pb_rechercher_liv->setObjectName(QStringLiteral("pb_rechercher_liv"));
        pb_rechercher_liv->setGeometry(QRect(980, 40, 91, 28));
        pb_rechercher_liv->setStyleSheet(QStringLiteral(""));
        pb_pdf_liv = new QPushButton(groupBox);
        pb_pdf_liv->setObjectName(QStringLiteral("pb_pdf_liv"));
        pb_pdf_liv->setGeometry(QRect(980, 330, 93, 28));
        pb_pdf_liv->setStyleSheet(QStringLiteral(""));
        groupBox_4 = new QGroupBox(groupBox);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 100, 411, 281));
        groupBox_4->setStyleSheet(QStringLiteral(""));
        label = new QLabel(groupBox_4);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 60, 81, 16));
        label->setStyleSheet(QStringLiteral(""));
        la_adresseliv = new QLineEdit(groupBox_4);
        la_adresseliv->setObjectName(QStringLiteral("la_adresseliv"));
        la_adresseliv->setGeometry(QRect(170, 140, 113, 22));
        la_adresseliv->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        le_id = new QLineEdit(groupBox_4);
        le_id->setObjectName(QStringLiteral("le_id"));
        le_id->setGeometry(QRect(170, 60, 111, 22));
        le_id->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        le_nomLiv = new QLineEdit(groupBox_4);
        le_nomLiv->setObjectName(QStringLiteral("le_nomLiv"));
        le_nomLiv->setGeometry(QRect(170, 180, 113, 22));
        le_nomLiv->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_2 = new QLabel(groupBox_4);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 100, 141, 16));
        label_2->setStyleSheet(QStringLiteral(""));
        label_13 = new QLabel(groupBox_4);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(20, 176, 81, 20));
        label_13->setStyleSheet(QStringLiteral(""));
        la_Dateliv = new QLineEdit(groupBox_4);
        la_Dateliv->setObjectName(QStringLiteral("la_Dateliv"));
        la_Dateliv->setGeometry(QRect(170, 100, 113, 22));
        la_Dateliv->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_3 = new QLabel(groupBox_4);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(20, 140, 55, 16));
        label_3->setStyleSheet(QStringLiteral(""));
        pb_Modifierliv_2 = new QPushButton(groupBox_4);
        pb_Modifierliv_2->setObjectName(QStringLiteral("pb_Modifierliv_2"));
        pb_Modifierliv_2->setGeometry(QRect(310, 60, 93, 28));
        pb_Modifierliv_2->setStyleSheet(QStringLiteral(""));
        pb_Modifierliv = new QPushButton(groupBox_4);
        pb_Modifierliv->setObjectName(QStringLiteral("pb_Modifierliv"));
        pb_Modifierliv->setGeometry(QRect(140, 250, 93, 28));
        pb_Modifierliv->setStyleSheet(QStringLiteral(""));
        pb_ajouterliv = new QPushButton(groupBox_4);
        pb_ajouterliv->setObjectName(QStringLiteral("pb_ajouterliv"));
        pb_ajouterliv->setGeometry(QRect(240, 250, 93, 28));
        pb_ajouterliv->setStyleSheet(QStringLiteral(""));
        label_24 = new QLabel(groupBox);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(10, 420, 21, 16));
        widget = new QWidget(groupBox);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(10, 480, 120, 80));
        widget->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/pics/Logo1.png);"));
        label_25 = new QLabel(groupBox);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(650, 40, 121, 20));
        widget_4 = new QWidget(groupBox);
        widget_4->setObjectName(QStringLiteral("widget_4"));
        widget_4->setGeometry(QRect(860, 420, 211, 151));
        widget_4->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/pics/Jarbou3.png);"));
        pushButton_4 = new QPushButton(groupBox);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(690, 530, 51, 41));
        pushButton_4->setStyleSheet(QLatin1String("image: url(:/new/prefix1/pics/soundOff.jpg);\n"
"background-image: url(:/new/prefix1/pics/soundOff.jpg);"));
        pushButton_3 = new QPushButton(groupBox);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(630, 530, 51, 41));
        pushButton_3->setStyleSheet(QLatin1String("background-image: url(:/new/prefix1/pics/soundonjpg.jpg);\n"
"image: url(:/new/prefix1/pics/soundonjpg.jpg);"));
        pb_rechercher_liv_2 = new QPushButton(groupBox);
        pb_rechercher_liv_2->setObjectName(QStringLiteral("pb_rechercher_liv_2"));
        pb_rechercher_liv_2->setGeometry(QRect(690, 420, 71, 28));
        pb_rechercher_liv_2->setStyleSheet(QStringLiteral(""));
        le_id_rech_liv1_2 = new QLineEdit(groupBox);
        le_id_rech_liv1_2->setObjectName(QStringLiteral("le_id_rech_liv1_2"));
        le_id_rech_liv1_2->setGeometry(QRect(500, 420, 181, 22));
        le_id_rech_liv1_2->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(500, 450, 81, 16));
        label_7->setStyleSheet(QStringLiteral("font: 11pt \"Franklin Gothic Medium\";"));
        label_8 = new QLabel(groupBox);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(230, 420, 271, 20));
        label_8->setStyleSheet(QStringLiteral(""));
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(230, 450, 181, 20));
        label_9->setStyleSheet(QStringLiteral(""));
        groupBox_4->raise();
        pb_supprimer_liv->raise();
        le_id_supp_liv->raise();
        tab_Livraisons->raise();
        le_id_rech_liv1->raise();
        pb_rechercher_liv->raise();
        pb_pdf_liv->raise();
        label_24->raise();
        widget->raise();
        label_25->raise();
        widget_4->raise();
        pushButton_4->raise();
        pushButton_3->raise();
        pb_rechercher_liv_2->raise();
        le_id_rech_liv1_2->raise();
        label_7->raise();
        label_8->raise();
        label_9->raise();
        tabWidget->addTab(La_Livraison, QString());
        La_commande = new QWidget();
        La_commande->setObjectName(QStringLiteral("La_commande"));
        groupBox_2 = new QGroupBox(La_commande);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(20, 40, 1081, 581));
        groupBox_2->setStyleSheet(QStringLiteral(""));
        pb_ajouterCom = new QPushButton(groupBox_2);
        pb_ajouterCom->setObjectName(QStringLiteral("pb_ajouterCom"));
        pb_ajouterCom->setGeometry(QRect(160, 350, 93, 28));
        pb_ajouterCom->setStyleSheet(QStringLiteral(""));
        tab_Commandes = new QTableView(groupBox_2);
        tab_Commandes->setObjectName(QStringLiteral("tab_Commandes"));
        tab_Commandes->setGeometry(QRect(480, 70, 581, 291));
        tab_Commandes->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        pb_supprimer_2 = new QPushButton(groupBox_2);
        pb_supprimer_2->setObjectName(QStringLiteral("pb_supprimer_2"));
        pb_supprimer_2->setGeometry(QRect(270, 440, 81, 28));
        pb_supprimer_2->setStyleSheet(QStringLiteral(""));
        le_id_supp_co = new QLineEdit(groupBox_2);
        le_id_supp_co->setObjectName(QStringLiteral("le_id_supp_co"));
        le_id_supp_co->setGeometry(QRect(130, 440, 121, 22));
        le_id_supp_co->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_11 = new QLabel(groupBox_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(90, 440, 21, 16));
        pb_trie_co = new QPushButton(groupBox_2);
        pb_trie_co->setObjectName(QStringLiteral("pb_trie_co"));
        pb_trie_co->setGeometry(QRect(860, 10, 141, 28));
        pb_trie_co->setStyleSheet(QStringLiteral(""));
        pb_date_co = new QPushButton(groupBox_2);
        pb_date_co->setObjectName(QStringLiteral("pb_date_co"));
        pb_date_co->setGeometry(QRect(860, 40, 141, 28));
        pb_date_co->setStyleSheet(QStringLiteral(""));
        groupBox_5 = new QGroupBox(groupBox_2);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 100, 411, 301));
        pb_Modifierliv_3 = new QPushButton(groupBox_5);
        pb_Modifierliv_3->setObjectName(QStringLiteral("pb_Modifierliv_3"));
        pb_Modifierliv_3->setGeometry(QRect(280, 50, 93, 28));
        pb_Modifierliv_3->setStyleSheet(QStringLiteral(""));
        pb_modifierCom = new QPushButton(groupBox_5);
        pb_modifierCom->setObjectName(QStringLiteral("pb_modifierCom"));
        pb_modifierCom->setGeometry(QRect(40, 250, 93, 28));
        pb_modifierCom->setStyleSheet(QStringLiteral(""));
        label_14 = new QLabel(groupBox_5);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(30, 170, 71, 16));
        le_id_2 = new QLineEdit(groupBox_5);
        le_id_2->setObjectName(QStringLiteral("le_id_2"));
        le_id_2->setGeometry(QRect(140, 50, 113, 22));
        le_id_2->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_6 = new QLabel(groupBox_5);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(30, 130, 55, 16));
        label_4 = new QLabel(groupBox_5);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(30, 50, 71, 16));
        le_Nom_Co = new QLineEdit(groupBox_5);
        le_Nom_Co->setObjectName(QStringLiteral("le_Nom_Co"));
        le_Nom_Co->setGeometry(QRect(140, 170, 113, 22));
        le_Nom_Co->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        le_prix_Com = new QLineEdit(groupBox_5);
        le_prix_Com->setObjectName(QStringLiteral("le_prix_Com"));
        le_prix_Com->setGeometry(QRect(140, 130, 113, 22));
        le_prix_Com->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_5 = new QLabel(groupBox_5);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(30, 90, 55, 16));
        label_15 = new QLabel(groupBox_5);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(30, 210, 81, 16));
        le_Email_CO = new QLineEdit(groupBox_5);
        le_Email_CO->setObjectName(QStringLiteral("le_Email_CO"));
        le_Email_CO->setGeometry(QRect(140, 210, 113, 22));
        le_Email_CO->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        le_qte_com = new QLineEdit(groupBox_5);
        le_qte_com->setObjectName(QStringLiteral("le_qte_com"));
        le_qte_com->setGeometry(QRect(140, 90, 113, 22));
        le_qte_com->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        pb_trie_co_2 = new QPushButton(groupBox_2);
        pb_trie_co_2->setObjectName(QStringLiteral("pb_trie_co_2"));
        pb_trie_co_2->setGeometry(QRect(590, 40, 141, 28));
        pb_trie_co_2->setStyleSheet(QStringLiteral(""));
        pb_date_co_2 = new QPushButton(groupBox_2);
        pb_date_co_2->setObjectName(QStringLiteral("pb_date_co_2"));
        pb_date_co_2->setGeometry(QRect(590, 10, 141, 28));
        pb_date_co_2->setStyleSheet(QStringLiteral(""));
        widget_2 = new QWidget(groupBox_2);
        widget_2->setObjectName(QStringLiteral("widget_2"));
        widget_2->setGeometry(QRect(10, 480, 120, 80));
        widget_2->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/pics/Logo1.png);"));
        widget_3 = new QWidget(groupBox_2);
        widget_3->setObjectName(QStringLiteral("widget_3"));
        widget_3->setGeometry(QRect(860, 420, 181, 141));
        widget_3->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/pics/Jarbou3.png);"));
        pushButton = new QPushButton(groupBox_2);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(630, 530, 51, 41));
        pushButton->setStyleSheet(QLatin1String("background-image: url(:/new/prefix1/pics/soundonjpg.jpg);\n"
"image: url(:/new/prefix1/pics/soundonjpg.jpg);"));
        pushButton_2 = new QPushButton(groupBox_2);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(690, 530, 51, 41));
        pushButton_2->setStyleSheet(QLatin1String("image: url(:/new/prefix1/pics/soundOff.jpg);\n"
"background-image: url(:/new/prefix1/pics/soundOff.jpg);"));
        label_31 = new QLabel(groupBox_2);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(500, 370, 111, 20));
        label_31->setStyleSheet(QStringLiteral(""));
        pb_rechercher_liv_5 = new QPushButton(groupBox_2);
        pb_rechercher_liv_5->setObjectName(QStringLiteral("pb_rechercher_liv_5"));
        pb_rechercher_liv_5->setGeometry(QRect(810, 370, 71, 28));
        pb_rechercher_liv_5->setStyleSheet(QStringLiteral(""));
        le_id_rech_liv1_5 = new QLineEdit(groupBox_2);
        le_id_rech_liv1_5->setObjectName(QStringLiteral("le_id_rech_liv1_5"));
        le_id_rech_liv1_5->setGeometry(QRect(620, 370, 181, 22));
        le_id_rech_liv1_5->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        label_32 = new QLabel(groupBox_2);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(700, 400, 81, 16));
        label_32->setStyleSheet(QStringLiteral("font: 11pt \"Franklin Gothic Medium\";"));
        label_33 = new QLabel(groupBox_2);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(700, 460, 81, 16));
        label_33->setStyleSheet(QStringLiteral("font: 11pt \"Franklin Gothic Medium\";"));
        label_34 = new QLabel(groupBox_2);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(700, 430, 81, 16));
        label_34->setStyleSheet(QStringLiteral("font: 11pt \"Franklin Gothic Medium\";"));
        label_35 = new QLabel(groupBox_2);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(500, 400, 161, 20));
        label_35->setStyleSheet(QStringLiteral(""));
        label_36 = new QLabel(groupBox_2);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(500, 430, 161, 20));
        label_36->setStyleSheet(QStringLiteral(""));
        label_37 = new QLabel(groupBox_2);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(500, 460, 191, 20));
        label_37->setStyleSheet(QStringLiteral(""));
        pb_rechercher_liv_6 = new QPushButton(groupBox_2);
        pb_rechercher_liv_6->setObjectName(QStringLiteral("pb_rechercher_liv_6"));
        pb_rechercher_liv_6->setGeometry(QRect(880, 370, 71, 28));
        pb_rechercher_liv_6->setStyleSheet(QStringLiteral(""));
        groupBox_5->raise();
        pb_ajouterCom->raise();
        tab_Commandes->raise();
        pb_supprimer_2->raise();
        le_id_supp_co->raise();
        label_11->raise();
        pb_trie_co->raise();
        pb_date_co->raise();
        pb_trie_co_2->raise();
        pb_date_co_2->raise();
        widget_2->raise();
        widget_3->raise();
        pushButton->raise();
        pushButton_2->raise();
        label_31->raise();
        pb_rechercher_liv_5->raise();
        le_id_rech_liv1_5->raise();
        label_32->raise();
        label_33->raise();
        label_34->raise();
        label_35->raise();
        label_36->raise();
        label_37->raise();
        pb_rechercher_liv_6->raise();
        tabWidget->addTab(La_commande, QString());
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        groupBox_3 = new QGroupBox(tab);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(0, 0, 381, 331));
        pushButton_6 = new QPushButton(groupBox_3);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(250, 30, 75, 28));
        pushButton_5 = new QPushButton(groupBox_3);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(169, 30, 75, 28));
        pushButton_7 = new QPushButton(groupBox_3);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(170, 96, 119, 28));
        pushButton_7->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/pics/Fullscreen.png);"));
        pushButton_8 = new QPushButton(groupBox_3);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(170, 230, 119, 28));
        pushButton_8->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/pics/Maximize.png);"));
        pushButton_9 = new QPushButton(groupBox_3);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(170, 163, 119, 28));
        pushButton_9->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/pics/Minimize.png);"));
        label_10 = new QLabel(groupBox_3);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(20, 40, 71, 16));
        label_12 = new QLabel(groupBox_3);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(20, 100, 71, 16));
        label_16 = new QLabel(groupBox_3);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(20, 170, 121, 16));
        label_17 = new QLabel(groupBox_3);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(20, 240, 121, 16));
        groupBox_6 = new QGroupBox(tab);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(390, 0, 341, 331));
        pushButton_26 = new QPushButton(groupBox_6);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(260, 60, 75, 28));
        pushButton_25 = new QPushButton(groupBox_6);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(181, 60, 75, 28));
        label_39 = new QLabel(groupBox_6);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(10, 70, 101, 16));
        label_40 = new QLabel(groupBox_6);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(150, 70, 20, 20));
        pushButton_27 = new QPushButton(groupBox_6);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(181, 110, 75, 28));
        label_41 = new QLabel(groupBox_6);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(150, 120, 21, 16));
        pushButton_28 = new QPushButton(groupBox_6);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(260, 110, 75, 28));
        label_42 = new QLabel(groupBox_6);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(10, 120, 101, 16));
        pushButton_11 = new QPushButton(groupBox_6);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(270, 180, 51, 41));
        pushButton_11->setStyleSheet(QLatin1String("image: url(:/new/prefix1/pics/soundOff.jpg);\n"
"background-image: url(:/new/prefix1/pics/soundOff.jpg);"));
        pushButton_10 = new QPushButton(groupBox_6);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(210, 180, 51, 41));
        pushButton_10->setStyleSheet(QLatin1String("background-image: url(:/new/prefix1/pics/soundonjpg.jpg);\n"
"image: url(:/new/prefix1/pics/soundonjpg.jpg);"));
        label_43 = new QLabel(groupBox_6);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(10, 200, 101, 16));
        widget_5 = new QWidget(tab);
        widget_5->setObjectName(QStringLiteral("widget_5"));
        widget_5->setGeometry(QRect(890, 480, 211, 151));
        widget_5->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/pics/Jarbou3.png);"));
        widget_6 = new QWidget(tab);
        widget_6->setObjectName(QStringLiteral("widget_6"));
        widget_6->setGeometry(QRect(0, 550, 120, 80));
        widget_6->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/pics/Logo1.png);"));
        groupBox_7 = new QGroupBox(tab);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(740, 0, 351, 331));
        pushButton_29 = new QPushButton(groupBox_7);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(100, 60, 121, 28));
        tabWidget->addTab(tab, QString());
        groupBox_7->raise();
        groupBox_3->raise();
        groupBox_6->raise();
        widget_5->raise();
        widget_6->raise();

        retranslateUi(GestionLivraisons);

        tabWidget->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(GestionLivraisons);
    } // setupUi

    void retranslateUi(QDialog *GestionLivraisons)
    {
        GestionLivraisons->setWindowTitle(QApplication::translate("GestionLivraisons", "The Pie Chart", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("GestionLivraisons", "Gestion Des Livraisons", Q_NULLPTR));
        pb_supprimer_liv->setText(QApplication::translate("GestionLivraisons", "Supprimer", Q_NULLPTR));
        pb_rechercher_liv->setText(QApplication::translate("GestionLivraisons", "rechercher", Q_NULLPTR));
        pb_pdf_liv->setText(QApplication::translate("GestionLivraisons", "Imprimer Pdf", Q_NULLPTR));
        groupBox_4->setTitle(QApplication::translate("GestionLivraisons", "Ajouter et Modifier", Q_NULLPTR));
        label->setText(QApplication::translate("GestionLivraisons", "Identifiant", Q_NULLPTR));
        label_2->setText(QApplication::translate("GestionLivraisons", "Date de la Livraison", Q_NULLPTR));
        label_13->setText(QApplication::translate("GestionLivraisons", "NomLivreur", Q_NULLPTR));
        label_3->setText(QApplication::translate("GestionLivraisons", "Adresse", Q_NULLPTR));
        pb_Modifierliv_2->setText(QApplication::translate("GestionLivraisons", "Afficher", Q_NULLPTR));
        pb_Modifierliv->setText(QApplication::translate("GestionLivraisons", "Modifier", Q_NULLPTR));
        pb_ajouterliv->setText(QApplication::translate("GestionLivraisons", "Ajouter", Q_NULLPTR));
        label_24->setText(QApplication::translate("GestionLivraisons", "Id", Q_NULLPTR));
        label_25->setText(QApplication::translate("GestionLivraisons", "Mot A Rechercher", Q_NULLPTR));
        pushButton_4->setText(QString());
        pushButton_3->setText(QString());
        pb_rechercher_liv_2->setText(QApplication::translate("GestionLivraisons", "Valider", Q_NULLPTR));
        label_7->setText(QApplication::translate("GestionLivraisons", "0", Q_NULLPTR));
        label_8->setText(QApplication::translate("GestionLivraisons", "Calcul du nombre de livraisons par date ", Q_NULLPTR));
        label_9->setText(QApplication::translate("GestionLivraisons", "Le nombre de livraisons est", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(La_Livraison), QApplication::translate("GestionLivraisons", "Livraisons", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("GestionLivraisons", "Gestion Des Commandes", Q_NULLPTR));
        pb_ajouterCom->setText(QApplication::translate("GestionLivraisons", "Ajouter", Q_NULLPTR));
        pb_supprimer_2->setText(QApplication::translate("GestionLivraisons", "Supprimer", Q_NULLPTR));
        label_11->setText(QApplication::translate("GestionLivraisons", "Id", Q_NULLPTR));
        pb_trie_co->setText(QApplication::translate("GestionLivraisons", "Trie par Quantit\303\251 asc", Q_NULLPTR));
        pb_date_co->setText(QApplication::translate("GestionLivraisons", "Trie par Quantit\303\251 Des", Q_NULLPTR));
        groupBox_5->setTitle(QApplication::translate("GestionLivraisons", "Ajouter Et Modifier", Q_NULLPTR));
        pb_Modifierliv_3->setText(QApplication::translate("GestionLivraisons", "Afficher", Q_NULLPTR));
        pb_modifierCom->setText(QApplication::translate("GestionLivraisons", "Modifier", Q_NULLPTR));
        label_14->setText(QApplication::translate("GestionLivraisons", "NomClient", Q_NULLPTR));
        label_6->setText(QApplication::translate("GestionLivraisons", "prix", Q_NULLPTR));
        label_4->setText(QApplication::translate("GestionLivraisons", "Identifiant", Q_NULLPTR));
        label_5->setText(QApplication::translate("GestionLivraisons", "Qte", Q_NULLPTR));
        label_15->setText(QApplication::translate("GestionLivraisons", "Emailclient", Q_NULLPTR));
        pb_trie_co_2->setText(QApplication::translate("GestionLivraisons", "Trie par Prix Des", Q_NULLPTR));
        pb_date_co_2->setText(QApplication::translate("GestionLivraisons", "Trie par Prix Asc", Q_NULLPTR));
        pushButton->setText(QString());
        pushButton_2->setText(QString());
        label_31->setText(QApplication::translate("GestionLivraisons", "D\303\251tails du Client", Q_NULLPTR));
        pb_rechercher_liv_5->setText(QApplication::translate("GestionLivraisons", "Valider", Q_NULLPTR));
        le_id_rech_liv1_5->setText(QString());
        label_32->setText(QApplication::translate("GestionLivraisons", "0", Q_NULLPTR));
        label_33->setText(QApplication::translate("GestionLivraisons", "0", Q_NULLPTR));
        label_34->setText(QApplication::translate("GestionLivraisons", "0", Q_NULLPTR));
        label_35->setText(QApplication::translate("GestionLivraisons", "Nombre de commandes", Q_NULLPTR));
        label_36->setText(QApplication::translate("GestionLivraisons", "Somme Depens\303\251", Q_NULLPTR));
        label_37->setText(QApplication::translate("GestionLivraisons", "Nombre d'articles Command\303\251", Q_NULLPTR));
        pb_rechercher_liv_6->setText(QApplication::translate("GestionLivraisons", "Mailing", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(La_commande), QApplication::translate("GestionLivraisons", "Commandes", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("GestionLivraisons", "Window Settings", Q_NULLPTR));
        pushButton_6->setText(QApplication::translate("GestionLivraisons", "Load", Q_NULLPTR));
        pushButton_5->setText(QApplication::translate("GestionLivraisons", "Save", Q_NULLPTR));
        pushButton_7->setText(QString());
        pushButton_8->setText(QString());
        pushButton_9->setText(QString());
        label_10->setText(QApplication::translate("GestionLivraisons", "Preset", Q_NULLPTR));
        label_12->setText(QApplication::translate("GestionLivraisons", "Fullscreen", Q_NULLPTR));
        label_16->setText(QApplication::translate("GestionLivraisons", "Minimize Window", Q_NULLPTR));
        label_17->setText(QApplication::translate("GestionLivraisons", "Maximize Window", Q_NULLPTR));
        groupBox_6->setTitle(QApplication::translate("GestionLivraisons", "SoundSettings", Q_NULLPTR));
        pushButton_26->setText(QApplication::translate("GestionLivraisons", "-", Q_NULLPTR));
        pushButton_25->setText(QApplication::translate("GestionLivraisons", "+", Q_NULLPTR));
        label_39->setText(QApplication::translate("GestionLivraisons", "Button Volume", Q_NULLPTR));
        label_40->setText(QApplication::translate("GestionLivraisons", "0", Q_NULLPTR));
        pushButton_27->setText(QApplication::translate("GestionLivraisons", "+", Q_NULLPTR));
        label_41->setText(QApplication::translate("GestionLivraisons", "0", Q_NULLPTR));
        pushButton_28->setText(QApplication::translate("GestionLivraisons", "-", Q_NULLPTR));
        label_42->setText(QApplication::translate("GestionLivraisons", "Music Volume", Q_NULLPTR));
        pushButton_11->setText(QString());
        pushButton_10->setText(QString());
        label_43->setText(QApplication::translate("GestionLivraisons", "Music On/Off", Q_NULLPTR));
        groupBox_7->setTitle(QApplication::translate("GestionLivraisons", "Font Settings", Q_NULLPTR));
        pushButton_29->setText(QApplication::translate("GestionLivraisons", "Change Font", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("GestionLivraisons", "Settings", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class GestionLivraisons: public Ui_GestionLivraisons {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GESTIONLIVRAISONS_H
